<?php

namespace PokedexBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * FicheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheRepository extends EntityRepository
{
    public function getFiches()
    {
        $query = $this->createQueryBuilder('f')
            ->leftJoin('f.image', 'i')
            ->addSelect('i')
            ->leftJoin('f.evolution', 'e')
            ->addSelect('e')
            ->orderBy('f.nationalID', 'ASC')
            ->getQuery();

        return $query->getResult();
    }
}
